recipe/recipe/urls.py
from django.urls import path

from . import views

app_name = 'recipe'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('<int:dish_id>/details/', views.dish_detail, name='dish_detail'),
    path('dishes/', views.dishes, name='dishes'),
    path('ingredients/', views.ingredients, name='ingredients'),
    path('<int:category_id>/category', views.category_detail, name='category_detail'),
    path('<int:ingredient_id>/ingredient_detail/', views.ingredient_detail, name='ingredient_detail'),
]

recipe/recipe_book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
]

recipe/recipe/models.py
from django.db import models


class Category(models.Model):
    """Категория блюда"""
    name = models.CharField(verbose_name='Название категории', max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'


class Dish(models.Model):
    """Название и описание рецепта блюда"""
    name = models.CharField(verbose_name='Название блюда', max_length=100)
    text = models.TextField(verbose_name='Рецепт', null=True, blank=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Блюда'
        verbose_name = 'Блюдо'


class Ingredient(models.Model):
    """Название ингредиента"""
    name = models.CharField(verbose_name='Название ингредиента', max_length=100, null=True, blank=True)
    dish = models.ManyToManyField(Dish, verbose_name='Название блюда')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Ингредиенты'
        verbose_name = 'Ингредиент'


class WeightOfIngredient(models.Model):
    """Вес ингредиента в граммах"""
    weight = models.FloatField(verbose_name='Вес в граммах', null=True, blank=True)
    ingredient = models.ForeignKey(Ingredient, verbose_name='Название ингредиента', on_delete=models.CASCADE, null=True, blank=True)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, verbose_name='Название блюда', null=True, blank=True)

    def __str__(self):
        return str(self.weight)

    class Meta:
        verbose_name_plural = 'Вес'
        verbose_name = 'Вес'


class AmountOfIngredient(models.Model):
    """Количество ингредиентов (штук)"""
    amount = models.IntegerField(verbose_name='Количество штук', null=True, blank=True)
    ingredient = models.ForeignKey(Ingredient, verbose_name='Название ингредиента', on_delete=models.CASCADE, null=True, blank=True)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, verbose_name='Название блюда',  null=True, blank=True)

    def __str__(self):
        return str(self.amount)

    class Meta:
        verbose_name_plural = 'Количество'
        verbose_name = 'Количество'

recipe/recipe/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Category, Dish, Ingredient, WeightOfIngredient, AmountOfIngredient

menu = [
    {'title': 'Главная', 'url_name': 'recipe:index'},
    {'title': 'Категории блюд', 'url_name': 'recipe:categories'},
    {'title': 'Все блюда', 'url_name': 'recipe:dishes'},
    {'title': 'Все ингредиенты', 'url_name': 'recipe:ingredients'},
]


def index(request):
    """Функция отображения главной страницы"""
    # context = {'title': 'Главная страница', 'menu': menu}
    query = request.GET.get('q')
    if query:
        dish = Dish.objects.filter(name__istartswith=query)
        ingredient = Ingredient.objects.filter(name__istartswith=query)
        if dish or ingredient:
            context = {'title': 'Результаты поиска', 'menu': menu, 'dish': dish, 'ingredient': ingredient}
            return render(request, 'recipe/index.html', context)
    context = {'title': 'Главная страница', 'menu': menu}
    return render(request, 'recipe/index.html', context)

def categories(request):
    """Функция отображения категорий"""
    category_list = Category.objects.all()
    context = {'title': 'Категории', 'menu': menu, 'category_list': category_list}
    return render(request, 'recipe/categories.html', context)


def dish_detail(request, dish_id):
    """Функция отображения блюда"""
    dish = Dish.objects.get(pk=dish_id)
    context = {'title': dish.name, 'menu': menu, 'dish': dish}
    return render(request, 'recipe/dish_detail.html', context)


def dishes(request):
    """Функция отображения всех блюд"""
    dish_list = Dish.objects.all()
    context = {'title': 'Блюда', 'menu': menu, 'dish_list': dish_list}
    return render(request, 'recipe/dishes.html', context)


def ingredients(request):
    """Функция отображения ингредиентов"""
    ingredient_list = Ingredient.objects.all()
    context = {'title': 'Ингредиенты', 'menu': menu, 'ingredient_list': ingredient_list}
    return render(request, 'recipe/ingredients.html', context)


def category_detail(request, category_id):
    """Функция отображения отдельной категории"""
    category = Category.objects.get(pk=category_id)
    context = {'title': category.name, 'menu': menu, 'category': category}
    return render(request, 'recipe/category_detail.html', context)


def ingredient_detail(request, ingredient_id):
    """Функция отображения ингредиентов"""
    ingredient = Ingredient.objects.get(pk=ingredient_id)
    context = {'title': 'Ингредиенты', 'menu': menu, 'ingredient': ingredient}
    return render(request, 'recipe/ingredient_detail.html', context)

recipe/recipe/templates/recipe/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'recipe/css/styles.css' %}" rel="stylesheet" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="wrapper">
{% block mainmenu %}
		<header>
			<ul class="menu">
	{% for m in menu %}
			<div class="menu-items"><li class="list-menu"><a href="{% url m.url_name %}">{{m.title}}</a></li></div>
	{% endfor %}
			</ul>
			<div class="clear"></div>
		</header>
{% endblock mainmenu %}

<!-- Блок контента -->
	<div class="container">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->

<!-- Footer -->
	<div>
		<p class="footer">&copy; 2021 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
	</div>
</div>
<!-- Конец footer'а и страницы -->
</body>
</html>

recipe/recipe/templates/recipe/categories.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if category_list %}
<div class="content">
<h1>Список категорий</h1>
<ul class="ul-items">
    {% for category in category_list %}
    <li class="items"><a class="a-content" href="{% url 'recipe:category_detail' category.id %}" >{{ category.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p> Нет категорий </p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/category_detail.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if category %}
<div class="content">
<h1>{{ category.name }}</h1>
<ul class="ul-items">
    {% for dish in category.dish_set.all %}
        <li class="items"><a class="a-content" href="{% url 'recipe:dish_detail' dish.id %}">{{ dish }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p> Нет блюд </p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/dish_detail.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if dish %}
<div class="content">
<h1>{{ dish.name }}</h1>
<p>{{ dish.text }}</p>
<ul><span>Вам понадобится:</span>
    <br>
    <br>
    {% for ingredient in dish.ingredient_set.all %}
        <li>{{ ingredient }} -
            {% for amount in ingredient.amountofingredient_set.all %}
                {% if amount.dish_id == dish.id %}
                    {{ amount }} шт.
                {% endif %}
            {% endfor %}
            {% for weight in ingredient.weightofingredient_set.all %}
                {% if weight.dish_id == dish.id %}
                    {{ weight }} грамм.
                {% endif %}
            {% endfor %}
        </li>
    {% endfor %}
</ul>
{% else %}
<p> Нет блюд </p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/dishes.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if dish_list %}
<div class="content">
<h1>Все блюда</h1>
<ul class="ul-items">
    {% for dish in dish_list %}
    <li class="items"><a class="a-content" href="{% url 'recipe:dish_detail' dish.id %}">{{ dish.name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p> Нет блюд </p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/index.html
{% extends 'recipe/base.html' %}

{% block content %}

<div class="search-box">
    <div class="container-1">
    <form action="" method="get">
        <input type="search" name="q" placeholder="Поиск..." required size="70">
        <i class="fa fa-search"></i>
    </form>
    </div>
</div>
{% if ingredient or dish%}
<div class="content">
    <br>
    <br>
    <span>Результаты поиска: </span>
    <br>
    <br>
    <ul class="ul-items">
        {% for d in dish %}
        <li class="items"><a class="a-content" href="{% url 'recipe:dish_detail' d.id %}">{{ d.name }}</a></li>
        {% endfor %}
        {% for i in ingredient %}
        <li class="items"><a class="a-content" href="{% url 'recipe:ingredient_detail' i.id %}">{{ i.name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% else %}
<div class="content">
<h1>Добро пожаловать на наш кулинарный сайт!</h1>
<p>Здесь вы можете просмотреть рецепты для приготовления разнообразных блюд, которые отлично подойдут, как на завтрак,
    так и на обед или ужин. Просто выберите интересующую Вас категорию.</p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/ingredient_detail.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if ingredient %}
<div class="content">
<h1>{{ ingredient.name }}</h1>
<ul>
    <li>{{ ingredient.name }}. Этот ингредиент можно встретить в таких блюдах, как:
        {% for dish in ingredient.dish.all %}
            {% if not forloop.last %}
                <span> {{ dish }}, </span>
            {% else %}
                <span>{{ dish }}.</span>
            {% endif %}
        {% endfor %}
    </li>
</ul>
{% else %}
<p> Нет ингредиентов </p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/ingredients.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if ingredient_list %}
<div class="content">
<h1>Все ингредиенты</h1>
<ul>
    {% for ingredient in ingredient_list %}
    <li>{{ ingredient.name }}. Этот ингредиент можно встретить в таких блюдах, как:
        {% for dish in ingredient.dish.all %}
            {% if not forloop.last %}
                <span> {{ dish }}, </span>
            {% else %}
                <span>{{ dish }}.</span>
            {% endif %}
        {% endfor %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p> Нет ингредиентов </p>
</div>
{% endif %}
{% endblock %}

recipe/recipe/templates/recipe/search_result.html
{% extends 'recipe/base.html' %}

{% block content %}
{% if dish_list %}
<div class="content">
<h1>Все блюда</h1>
<ul class="ul-items">
    {% for dish in dish_list %}
    <li class="items"><center><a class="a-content" href="{% url 'recipe:dish_detail' dish.id %}">{{ dish.name }}</a></center></li>
    {% endfor %}
</ul>
{% else %}
<p> Нет блюд </p>
</div>
{% endif %}
{% endblock %}